# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  foodnetwork:

services:
  ca.farmer.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-farmer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.farmer.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a7fd9dae81fb91c2de9734fb2d98389852237064a5d1d44bd097a1fd2b188c9b_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.farmer.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a7fd9dae81fb91c2de9734fb2d98389852237064a5d1d44bd097a1fd2b188c9b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/farmer.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_farmer
    networks:
      - foodnetwork

  ca.government.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-government
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.government.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c9d9ae054f6118eed63382da5b09f07f1200db32ce80daabb473b3f5bc838a37_sk
      - FABRIC_CA_SERVER_PORT=7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.government.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c9d9ae054f6118eed63382da5b09f07f1200db32ce80daabb473b3f5bc838a37_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/government.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_government
    networks:
      - foodnetwork

  ca.supermarket.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-supermarket
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supermarket.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a55c1ada274221c110c9e5f21681d90df930ad6ae18a2e954c020f51aa0ae796_sk
      - FABRIC_CA_SERVER_PORT=7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.supermarket.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a55c1ada274221c110c9e5f21681d90df930ad6ae18a2e954c020f51aa0ae796_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/supermarket.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_supermarket
    networks:
      - foodnetwork

  ca.transport.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-transport
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.transport.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c19e763a21920cc0951deafb7af6e638cc3f2450d5f31b4a1a98fbe80f94ca69_sk
      - FABRIC_CA_SERVER_PORT=7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.transport.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c19e763a21920cc0951deafb7af6e638cc3f2450d5f31b4a1a98fbe80f94ca69_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/transport.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_transport
    networks:
      - foodnetwork